[project]
name = "gocardless-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "jinja2>=3.1.5",
    "pydantic>=2.10.4",
]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]
